/**
 * Permission mappings per canonical HMS role catalog.
 */

const { ROLES } = require('@config/roles');

const PERMISSIONS = Object.freeze({
  PROFILE_READ: 'profile:read',
  PROFILE_UPDATE: 'profile:update',
  PATIENT_READ: 'patient:read',
  PATIENT_WRITE: 'patient:write',
  PATIENT_DELETE: 'patient:delete',
  CLINICAL_READ: 'clinical:read',
  CLINICAL_WRITE: 'clinical:write',
  EMERGENCY_READ: 'emergency:read',
  EMERGENCY_WRITE: 'emergency:write',
  EMERGENCY_DELETE: 'emergency:delete',
  LAB_READ: 'lab:read',
  LAB_WRITE: 'lab:write',
  PHARMACY_READ: 'pharmacy:read',
  PHARMACY_WRITE: 'pharmacy:write',
  BILLING_READ: 'billing:read',
  BILLING_WRITE: 'billing:write',
  OPERATIONS_READ: 'operations:read',
  OPERATIONS_WRITE: 'operations:write',
  HR_READ: 'hr:read',
  HR_WRITE: 'hr:write',
  BIOMED_READ: 'biomed:read',
  BIOMED_WRITE: 'biomed:write',
  FACILITY_ADMIN: 'facility:admin',
  TENANT_ADMIN: 'tenant:admin',
  SYSTEM_ADMIN: 'system:admin'
});

const ROLE_PERMISSIONS = Object.freeze({
  [ROLES.SUPER_ADMIN]: Object.values(PERMISSIONS),
  [ROLES.TENANT_ADMIN]: [
    PERMISSIONS.TENANT_ADMIN,
    PERMISSIONS.FACILITY_ADMIN,
    PERMISSIONS.PROFILE_READ,
    PERMISSIONS.PROFILE_UPDATE,
    PERMISSIONS.PATIENT_READ,
    PERMISSIONS.PATIENT_WRITE,
    PERMISSIONS.PATIENT_DELETE,
    PERMISSIONS.CLINICAL_READ,
    PERMISSIONS.CLINICAL_WRITE,
    PERMISSIONS.EMERGENCY_READ,
    PERMISSIONS.EMERGENCY_WRITE,
    PERMISSIONS.EMERGENCY_DELETE,
    PERMISSIONS.LAB_READ,
    PERMISSIONS.LAB_WRITE,
    PERMISSIONS.PHARMACY_READ,
    PERMISSIONS.PHARMACY_WRITE,
    PERMISSIONS.BILLING_READ,
    PERMISSIONS.BILLING_WRITE,
    PERMISSIONS.OPERATIONS_READ,
    PERMISSIONS.OPERATIONS_WRITE,
    PERMISSIONS.HR_READ,
    PERMISSIONS.HR_WRITE,
    PERMISSIONS.BIOMED_READ,
    PERMISSIONS.BIOMED_WRITE
  ],
  [ROLES.FACILITY_ADMIN]: [
    PERMISSIONS.FACILITY_ADMIN,
    PERMISSIONS.PROFILE_READ,
    PERMISSIONS.PROFILE_UPDATE,
    PERMISSIONS.PATIENT_READ,
    PERMISSIONS.PATIENT_WRITE,
    PERMISSIONS.PATIENT_DELETE,
    PERMISSIONS.CLINICAL_READ,
    PERMISSIONS.CLINICAL_WRITE,
    PERMISSIONS.EMERGENCY_READ,
    PERMISSIONS.EMERGENCY_WRITE,
    PERMISSIONS.EMERGENCY_DELETE,
    PERMISSIONS.LAB_READ,
    PERMISSIONS.LAB_WRITE,
    PERMISSIONS.PHARMACY_READ,
    PERMISSIONS.PHARMACY_WRITE,
    PERMISSIONS.BILLING_READ,
    PERMISSIONS.BILLING_WRITE,
    PERMISSIONS.OPERATIONS_READ,
    PERMISSIONS.OPERATIONS_WRITE,
    PERMISSIONS.HR_READ,
    PERMISSIONS.HR_WRITE,
    PERMISSIONS.BIOMED_READ,
    PERMISSIONS.BIOMED_WRITE
  ],
  [ROLES.DOCTOR]: [
    PERMISSIONS.CLINICAL_READ,
    PERMISSIONS.CLINICAL_WRITE,
    PERMISSIONS.EMERGENCY_READ,
    PERMISSIONS.EMERGENCY_WRITE,
    PERMISSIONS.PROFILE_READ,
    PERMISSIONS.PATIENT_READ,
    PERMISSIONS.PATIENT_WRITE
  ],
  [ROLES.NURSE]: [
    PERMISSIONS.CLINICAL_READ,
    PERMISSIONS.CLINICAL_WRITE,
    PERMISSIONS.EMERGENCY_READ,
    PERMISSIONS.EMERGENCY_WRITE,
    PERMISSIONS.PROFILE_READ,
    PERMISSIONS.PATIENT_READ,
    PERMISSIONS.PATIENT_WRITE
  ],
  [ROLES.LAB_TECH]: [PERMISSIONS.LAB_READ, PERMISSIONS.LAB_WRITE, PERMISSIONS.PROFILE_READ],
  [ROLES.PHARMACIST]: [PERMISSIONS.PHARMACY_READ, PERMISSIONS.PHARMACY_WRITE, PERMISSIONS.PROFILE_READ],
  [ROLES.RECEPTIONIST]: [
    PERMISSIONS.PROFILE_READ,
    PERMISSIONS.PROFILE_UPDATE,
    PERMISSIONS.OPERATIONS_READ,
    PERMISSIONS.PATIENT_READ,
    PERMISSIONS.PATIENT_WRITE
  ],
  [ROLES.BILLING]: [PERMISSIONS.BILLING_READ, PERMISSIONS.BILLING_WRITE, PERMISSIONS.PROFILE_READ],
  [ROLES.OPERATIONS]: [PERMISSIONS.OPERATIONS_READ, PERMISSIONS.OPERATIONS_WRITE, PERMISSIONS.PROFILE_READ],
  [ROLES.HR]: [PERMISSIONS.HR_READ, PERMISSIONS.HR_WRITE, PERMISSIONS.PROFILE_READ],
  [ROLES.BIOMED]: [PERMISSIONS.BIOMED_READ, PERMISSIONS.BIOMED_WRITE, PERMISSIONS.PROFILE_READ],
  [ROLES.HOUSE_KEEPER]: [PERMISSIONS.OPERATIONS_READ, PERMISSIONS.PROFILE_READ, PERMISSIONS.PATIENT_READ],
  [ROLES.AMBULANCE_OPERATOR]: [
    PERMISSIONS.PROFILE_READ,
    PERMISSIONS.EMERGENCY_READ,
    PERMISSIONS.EMERGENCY_WRITE
  ],
  [ROLES.PATIENT]: [PERMISSIONS.PROFILE_READ, PERMISSIONS.PROFILE_UPDATE, PERMISSIONS.PATIENT_READ],
  [ROLES.OTHER]: [PERMISSIONS.PROFILE_READ, PERMISSIONS.PATIENT_READ]
});

module.exports = {
  PERMISSIONS,
  ROLE_PERMISSIONS
};
